version: '3'

services:
  nginx:
    image: mushfiqurgalib/client
    build: .
    restart: unless-stopped
    ports:
      - 100:100
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - userservice
      - statusservice
      - storyservice
    


  # clientservice:
  #   build: ./client
  #   restart: unless-stopped
      

  userservice:
    image: mushfiqurgalib/userservice
    build: ./server/User
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'users'
    volumes:
     - ./server/userdb:/docker-entrypoint-initdb.d
     - mysqluser:/var/lib/mysql

  statusservice:
    image: mushfiqurgalib/statusservice
    build: ./server/Status
    restart: unless-stopped
    depends_on:
      - statusdb 

  statusdb:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'status'
    volumes:
     - ./server/statusdb:/docker-entrypoint-initdb.d
     -  mysqlstatus:/var/lib/mysql  

  storyservice:
    image: mushfiqurgalib/storyservice
    build: ./server/Story
    restart: unless-stopped
    depends_on:
      - storydb
      - storyobjectdb 

  storydb:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'story'
    volumes:
     - ./server/storydb:/docker-entrypoint-initdb.d
     -  mysqlstory:/var/lib/mysql  

  storyobjectdb:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server --address 0.0.0.0:9000 --console-address ":9001" /data
    volumes:
      - storyobjectdata:/data             

volumes:
  mysqluser:
  mysqlstatus:
  mysqlstory:
  storyobjectdata:
  
