version: '3'

services:
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - 100:100
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - userservice
      - statusservice
      - storyservice
    

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   ports: 
  #     - 8077:80
  #   environment:
  #     - PMA_HOST= db
  #   depends_on:
  #     - db
    

  userservice:
    build: ./User
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'users'
    volumes:
     - ./userdb:/docker-entrypoint-initdb.d
     - mysqluser:/var/lib/mysql

  statusservice:
    build: ./Status
    restart: unless-stopped
    depends_on:
      - statusdb 

  statusdb:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'status'
    volumes:
     - ./statusdb:/docker-entrypoint-initdb.d
     -  mysqlstatus:/var/lib/mysql  

  storyservice:
    build: ./Story
    restart: unless-stopped
    depends_on:
      - storydb
      - storyobjectdb 

  storydb:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'story'
    volumes:
     - ./storydb:/docker-entrypoint-initdb.d
     -  mysqlstory:/var/lib/mysql  

  storyobjectdb:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server --address 0.0.0.0:9000 --console-address ":9001" /data
    volumes:
      - storyobjectdata:/data             

volumes:
  mysqluser:
  mysqlstatus:
  mysqlstory:
  storyobjectdata:
  
